### ISSUE TITLE
Strange step bump in custom data

### ISSUE THREAD

**Issue by WXizhi** [hoshino042/bilateral_normal_integration#8]
Hello, thank you for sharing the amazing work!
I tried to run normal integration on my data in perspective case with the normal map(obtained through 2DGS) and the intrinsic matrix, however, there are alway wrong step bumps in the result.  And, when the depth map(also obtained through 2DGS) is provided, the bumps appeare even more.
Havent figured it out for several days. could you please drop some hints? thanks a lot.
![image](https://github.com/user-attachments/assets/e034bbad-f5a2-43d2-8833-f4bca798ca9a)

here is my data:
[test3.zip](https://github.com/user-attachments/files/18020689/test3.zip)

**Comment by xucao-42** [comment]
You can set smaller _k_, e.g., k=1. 
A smaller k makes the surface "tougher" to split, as illustrated in [Fig. 8](https://drive.google.com/file/d/17eB96Yr40wouCacoLMpQdfXgQ5PEDgkT/view).

Another workaround is to segment the RGB images into patches and perform normal integration for different patches independently. Reference: [SuperPrimitives](https://makezur.github.io/SuperPrimitive/).

**Comment by WXizhi** [comment]
> You can set smaller _k_, e.g., k=1. A smaller k makes the surface "tougher" to split, as illustrated in [Fig. 8](https://drive.google.com/file/d/17eB96Yr40wouCacoLMpQdfXgQ5PEDgkT/view).
> 
> Another workaround is to segment the RGB images into patches and perform normal integration for different patches independently. Reference: [SuperPrimitives](https://makezur.github.io/SuperPrimitive/).

thank you for the reply!
